//Object de sons
var sounds = new function(){
	this.impact = new Audio("sound/impact.wav");
	this.bullet = new Audio("sound/playerattack.wav");
	this.gold = new Audio("sound/gold.wav");
	this.enemyDeath = new Audio("sound/enemydeath.wav");
	this.playerDmg = new Audio("sound/playerdmg.wav");
	this.playerDeath = new Audio("sound/playerdeath.wav");
};
//Object d'images
var imageTool = new function() {
	//Minimap
	this.visited = new Image();
	this.unvisited = new Image();
	this.current = new Image();
	this.boss = new Image();
	this.shop = new Image();
	this.treasure = new Image();
	//Game
	this.tutorial = new Image();
	this.ui = new Image();
	this.background = new Image();
	this.pauseScreen = new Image();
	this.loading = new Image();
	this.blackScreen = new Image();
	this.hp = new Image();
	this.halfHp = new Image();
	this.ap = new Image();
	this.halfAp = new Image();
	this.emptyHp = new Image();
	this.playerDead = new Image();
	this.playerDown = new Image();
	this.playerLeft = new Image();
	this.playerUp = new Image();
	this.playerRight = new Image();
	this.playerBullet = new Image();
	this.pBulletAnim = new Image();
	this.eBulletAnim = new Image();
	this.bulletNumberOne= new Image();
	this.animNumberOne= new Image();
	this.explosion = new Image();
	this.explosionmark = new Image();
	this.flyBoss = new Image();
	this.flyBossHit = new Image();
	this.fly = new Image();
	this.fly1 = new Image();
	this.flyAnim = new Image();
	this.flyHit = new Image();
	this.towerHit = new Image();
	this.tower = new Image();
	this.enemyBullet = new Image();
	this.block = new Image();
	this.block1 = new Image();
	this.block2 = new Image();
	this.xblock = new Image();
	this.glue = new Image();
	this.hole = new Image();
	this.gold = new Image();
	this.keys = new Image();
	this.bombs = new Image();
	this.shadow = new Image();
	this.blood1 = new Image();
	this.blood2 = new Image();
	this.blood3 = new Image();
	this.bloodRoom = new Image();
	this.bossBar = new Image();
	this.bossBg = new Image();
	this.bossHp = new Image();
	this.bossHpHit = new Image();
	this.bloodAnim = new Image();
	this.bodyAnim = new Image();
	this.bodyRight = new Image();
	this.bodyLeft = new Image();
	this.bodyIdle = new Image();
	this.eBodyIdle = new Image();
	this.eBodyRight = new Image();
	this.eBodyLeft = new Image();
	this.mulliganhead = new Image();
	this.hitBox = new Image();
	this.doorL = new Image();
	this.doorR = new Image();
	this.doorU = new Image();
	this.doorD = new Image();
	this.doorLclosed = new Image();
	this.doorRclosed = new Image();
	this.doorUclosed = new Image();
	this.doorDclosed = new Image();
	this.bossBg = new Image();
	this.spiderIdleAnim = new Image();
	this.spiderMoveAnim = new Image();
	this.spiderHit = new Image();
	this.spiderButt = new Image();
	this.spiderButtHit = new Image();
	this.poop1 = new Image();
	this.poop2 = new Image();
	this.poop3 = new Image();
	this.poop4 = new Image();
	this.poop5 = new Image();
	this.poopAnim = new Image();
	this.barrel1 = new Image();
	this.barrel2 = new Image();
	this.barrel3 = new Image();
	this.barrel4 = new Image();
	//ITEMS
	this.coin = new Image();
	this.bomb = new Image();
	this.armor = new Image();
	this.health = new Image();
	this.halfhealth = new Image();
	this.nickel = new Image();
	this.dime = new Image();
	this.key = new Image();
	this.boom = new Image();
	this.breakfast = new Image();
	this.bucketoflard = new Image();
	this.dessert = new Image();
	this.dinner = new Image();
	this.growthhormones = new Image();
	this.jesusjuice= new Image();
	this.lunch = new Image();
	this.magicmushroom = new Image();
	this.maxshead = new Image();
	this.meat  = new Image();
	this.minimushroom  = new Image();
	this.momsheels  = new Image();
	this.momslipstick  = new Image();
	this.momsunderwear  = new Image();
	this.numberone  = new Image();
	this.pyro  = new Image();
	this.rawliver  = new Image();
	this.redheart  = new Image();
	this.roidrage  = new Image();
	this.rottenmeat  = new Image();
	this.skeletonkey  = new Image();
	this.speedball  = new Image();
	this.thebelt  = new Image();
	this.thehalo  = new Image();
	this.thesadonion  = new Image();
	this.thesmallrock  = new Image();
	this.toothpicks  = new Image();
	this.wirecoathanger  = new Image();
	this.woodenspoon  = new Image();
	this.wiggleworm  = new Image();
	//Préchargement
	var numImages = 128;
	var numLoaded = 0;
	function imageLoaded() {
		numLoaded++;
		if (numLoaded === numImages) {gameInit(); loading(false);}
		else loading(true); }
		
	this.visited.onload = function() {imageLoaded();}
	this.unvisited.onload = function() {imageLoaded();}
	this.current.onload = function() {imageLoaded();}
	this.boss.onload = function() {imageLoaded();}
	this.shop.onload = function() {imageLoaded();}
	this.treasure.onload = function() {imageLoaded();}
	
	this.tutorial.onload = function() {imageLoaded();}
	this.ui.onload = function() {imageLoaded();}
	this.background.onload = function() {imageLoaded();}
	this.pauseScreen.onload = function() {imageLoaded();}
	this.loading.onload = function() {imageLoaded();}
	this.blackScreen.onload = function() {imageLoaded();}
	this.hp.onload = function() {imageLoaded();}
	this.halfHp.onload = function() {imageLoaded();}
	this.ap.onload = function() {imageLoaded();}
	this.halfAp.onload = function() {imageLoaded();}
	this.emptyHp.onload = function() {imageLoaded();}
	this.playerDead.onload = function() {imageLoaded();}
	this.playerDown.onload = function() {imageLoaded();}
	this.playerLeft.onload = function() {imageLoaded();}
	this.playerUp.onload = function() {imageLoaded();}
	this.playerRight.onload = function() {imageLoaded();}
	this.playerBullet.onload = function() {imageLoaded();}
	this.pBulletAnim.onload = function() {imageLoaded();}
	this.eBulletAnim.onload = function() {imageLoaded();}
	this.bulletNumberOne.onload = function() {imageLoaded();}
	this.animNumberOne.onload = function() {imageLoaded();}
	this.explosion.onload = function() {imageLoaded();}
	this.explosionmark.onload = function() {imageLoaded();}
	this.flyBoss.onload = function() {imageLoaded();}
	this.flyBossHit.onload = function() {imageLoaded();}
	this.fly.onload = function() {imageLoaded();}
	this.fly1.onload = function() {imageLoaded();}
	this.flyAnim.onload = function() {imageLoaded();}
	this.flyHit.onload = function() {imageLoaded();}
	this.towerHit.onload = function() {imageLoaded();}
	this.tower.onload = function() {imageLoaded();}
	this.enemyBullet.onload = function() {imageLoaded();}
	this.block.onload = function() {imageLoaded();}
	this.block1.onload = function() {imageLoaded();}
	this.block2.onload = function() {imageLoaded();}
	this.xblock.onload = function() {imageLoaded();}
	this.glue.onload = function() {imageLoaded();}
	this.hole.onload = function() {imageLoaded();}
	this.gold.onload = function() {imageLoaded();}
	this.keys.onload = function() {imageLoaded();}
	this.bombs.onload = function() {imageLoaded();}
	this.shadow.onload = function() {imageLoaded();}
	this.blood1.onload = function() {imageLoaded();}
	this.blood2.onload = function() {imageLoaded();}
	this.blood3.onload = function() {imageLoaded();}
	this.bloodRoom.onload = function() {imageLoaded();}
	this.bloodAnim.onload = function() {imageLoaded();}
	this.bodyAnim.onload = function() {imageLoaded();}
	this.bodyRight.onload = function() {imageLoaded();}
	this.bodyLeft.onload = function() {imageLoaded();}
	this.bodyIdle.onload = function() {imageLoaded();}
	this.eBodyIdle.onload = function() {imageLoaded();}
	this.eBodyRight.onload = function() {imageLoaded();}
	this.eBodyLeft.onload = function() {imageLoaded();}
	this.mulliganhead.onload = function() {imageLoaded();}
	this.hitBox.onload = function() {imageLoaded();}
	this.doorL.onload = function() {imageLoaded();}
	this.doorR.onload = function() {imageLoaded();}
	this.doorU.onload = function() {imageLoaded();}
	this.doorD.onload = function() {imageLoaded();}
	this.doorUclosed.onload = function() {imageLoaded();}
	this.doorDclosed.onload = function() {imageLoaded();}
	this.doorLclosed.onload = function() {imageLoaded();}
	this.doorRclosed.onload = function() {imageLoaded();}
	this.bossBar.onload = function() {imageLoaded();}
	this.bossBg.onload = function() {imageLoaded();}
	this.bossHp.onload = function() {imageLoaded();}
	this.bossHpHit.onload = function() {imageLoaded();}
	this.spiderIdleAnim.onload = function() {imageLoaded();}
	this.spiderMoveAnim.onload = function() {imageLoaded();}
	this.spiderHit.onload = function() {imageLoaded();}
	this.spiderButt.onload = function() {imageLoaded();}
	this.spiderButtHit.onload = function() {imageLoaded();}
	this.poop1.onload = function() {imageLoaded();}
	this.poop2.onload = function() {imageLoaded();}
	this.poop3.onload = function() {imageLoaded();}
	this.poop4.onload = function() {imageLoaded();}
	this.poop5.onload = function() {imageLoaded();}
	this.poopAnim.onload = function() {imageLoaded();}
	this.barrel1.onload = function() {imageLoaded();}
	this.barrel2.onload = function() {imageLoaded();}
	this.barrel3.onload = function() {imageLoaded();}
	this.barrel4.onload = function() {imageLoaded();}
	//ITEMS
	this.coin.onload = function() {imageLoaded();}
	this.bomb.onload = function() {imageLoaded();}
	this.armor.onload = function() {imageLoaded();}
	this.health.onload = function() {imageLoaded();}
	this.halfhealth.onload = function() {imageLoaded();}
	this.nickel.onload = function() {imageLoaded();}
	this.dime.onload = function() {imageLoaded();}
	this.key.onload = function() {imageLoaded();}
	this.boom.onload = function() {imageLoaded();}
	this.breakfast.onload = function() {imageLoaded();}
	this.bucketoflard.onload = function() {imageLoaded();}
	this.dessert.onload = function() {imageLoaded();}
	this.dinner.onload = function() {imageLoaded();}
	this.growthhormones.onload = function() {imageLoaded();}
	this.jesusjuice.onload = function() {imageLoaded();}
	this.lunch.onload = function() {imageLoaded();}
	this.magicmushroom.onload = function() {imageLoaded();}
	this.maxshead.onload = function() {imageLoaded();}
	this.meat.onload = function() {imageLoaded();}
	this.minimushroom.onload = function() {imageLoaded();}
	this.momsheels.onload = function() {imageLoaded();}
	this.momslipstick.onload = function() {imageLoaded();}
	this.momsunderwear.onload = function() {imageLoaded();}
	this.numberone.onload = function() {imageLoaded();}
	this.pyro.onload = function() {imageLoaded();}
	this.rawliver.onload = function() {imageLoaded();}
	this.redheart.onload = function() {imageLoaded();}
	this.roidrage.onload = function() {imageLoaded();}
	this.rottenmeat.onload = function() {imageLoaded();}
	this.skeletonkey.onload = function() {imageLoaded();}
	this.speedball.onload = function() {imageLoaded();}
	this.thebelt.onload = function() {imageLoaded();}
	this.thehalo.onload = function() {imageLoaded();}
	this.thesadonion.onload = function() {imageLoaded();}
	this.thesmallrock.onload = function() {imageLoaded();}
	this.toothpicks.onload = function() {imageLoaded();}
	this.wirecoathanger.onload = function() {imageLoaded();}
	this.woodenspoon.onload = function() {imageLoaded();}
	this.wiggleworm.onload = function() {imageLoaded();}
	//Sources
	this.visited.src = "img/minimap/visited.png";
	this.unvisited.src = "img/minimap/unvisited.png";
	this.current.src = "img/minimap/current.png";
	this.boss.src = "img/minimap/boss.png";
	this.shop.src = "img/minimap/shop.png";
	this.treasure.src = "img/minimap/treasure.png";
	
	this.tutorial.src = "img/tutorial.png";
	this.ui.src = "img/ui.png";
	this.background.src = "img/bg.png";
	this.pauseScreen.src = "img/pause.png";
	this.loading.src = "img/loading.png";
	this.blackScreen.src = "img/screen.png";
	this.hp.src = "img/hp.png";
	this.halfHp.src = "img/halfhp.png";
	this.ap.src = "img/armor.png";
	this.halfAp.src = "img/halfarmor.png";
	this.emptyHp.src = "img/emptyhp.png";
	this.towerHit.src = "img/towerhit.png";
	this.flyBoss.src = "img/flyboss.png";
	this.flyBossHit.src = "img/flybosshit.png";
	this.fly.src = "img/fly.png";
	this.fly1.src = "img/fly1.png";
	this.flyAnim.src = "img/flyanim.png";
	this.flyHit.src = "img/flyhit.png";
	this.playerDead.src = "img/playerdead.png";
	this.playerDown.src = "img/player.png";
	this.playerLeft.src = "img/player1.png";
	this.playerUp.src = "img/player2.png";
	this.playerRight.src = "img/player3.png";
	this.playerBullet.src = "img/bullet.png";
	this.pBulletAnim.src = "img/pbulletanim.png";
	this.bulletNumberOne.src = "img/bulletnumberone.png";
	this.animNumberOne.src = "img/numberonebulletanim.png";
	this.eBulletAnim.src = "img/ebulletanim.png";
	this.explosion.src = "img/explosion.png";
	this.explosionmark.src = "img/explosionmark.png";
	this.tower.src = "img/tower.png";
	this.enemyBullet.src = "img/enemybullet.png";
	this.block.src = "img/block.png";
	this.block1.src = "img/block1.png";
	this.block2.src = "img/block2.png";
	this.xblock.src = "img/block3.png";
	this.glue.src = "img/glue.png";
	this.hole.src = "img/hole.png";
	this.gold.src = "img/gold.png";
	this.keys.src = "img/keys.png";
	this.bombs.src = "img/bombs.png";
	this.shadow.src = "img/shadow.png";
	this.blood1.src = "img/blood1.png";
	this.blood2.src = "img/blood2.png";
	this.blood3.src = "img/blood3.png";
	this.bloodRoom.src = "img/bloodroom.png";
	this.bloodAnim.src = "img/bloodanimation.png";
	this.bodyAnim.src = "img/bodyanimation.png";
	this.bodyRight.src = "img/bodyanimationright.png";
	this.bodyLeft.src = "img/bodyanimationleft.png";
	this.bodyIdle.src = "img/bodyidle.png";
	this.eBodyIdle.src = "img/ebodyidle.png";
	this.eBodyRight.src = "img/ebodyanimationright.png";
	this.eBodyLeft.src = "img/ebodyanimationleft.png";
	this.mulliganhead.src = "img/mulliganhead.png";
	this.hitBox.src = "img/hit.png";
	this.doorL.src = "img/doorleft.png";
	this.doorR.src = "img/doorright.png";
	this.doorU.src = "img/doorup.png";
	this.doorD.src = "img/doordown.png";
	this.doorUclosed.src = "img/closeddoorup.png";
	this.doorDclosed.src = "img/closeddoordown.png";
	this.doorLclosed.src = "img/closeddoorleft.png";
	this.doorRclosed.src = "img/closeddoorright.png";
	this.bossBar.src = "img/bossbar.png";
	this.bossBg.src = "img/bossbg.png";
	this.bossHp.src = "img/bosshp.png";
	this.bossHpHit.src = "img/bosshphit.png";
	this.spiderIdleAnim.src = "img/spideridleanim.png";
	this.spiderMoveAnim.src = "img/spidermoveanim.png";
	this.spiderHit.src = "img/spiderhit.png";
	this.spiderButt.src = "img/spiderbutt.png";
	this.spiderButtHit.src = "img/spiderbutthit.png";
	this.poop1.src = "img/poop1.png";
	this.poop2.src = "img/poop2.png";
	this.poop3.src = "img/poop3.png";
	this.poop4.src = "img/poop4.png";
	this.poop5.src = "img/poop5.png";
	this.poopAnim.src = "img/poopanimation.png";
	this.barrel1.src = "img/barrel1.png";
	this.barrel2.src = "img/barrel2.png";
	this.barrel3.src = "img/barrel3.png";
	this.barrel4.src = "img/barrel4.png";
	//ITEMS
	this.coin.src = "img/items/coin.png";
	this.bomb.src = "img/items/bomb.png";
	this.armor.src = "img/items/armor.png";
	this.health.src = "img/items/health.png";
	this.halfhealth.src = "img/items/halfhealth.png";
	this.nickel.src = "img/items/nickel.png";
	this.dime.src = "img/items/dime.png";
	this.key.src = "img/items/key.png";
	this.boom.src = "img/items/boom.png";
	this.breakfast.src = "img/items/breakfast.png";
	this.bucketoflard.src = "img/items/bucketoflard.png";
	this.dessert.src = "img/items/dessert.png";
	this.dinner.src = "img/items/dinner.png";
	this.growthhormones.src = "img/items/growthhormones.png";
	this.jesusjuice.src = "img/items/jesusjuice.png";
	this.lunch.src = "img/items/lunch.png";
	this.magicmushroom.src = "img/items/magicmushroom.png";
	this.maxshead.src = "img/items/maxshead.png";
	this.meat.src = "img/items/meat.png";
	this.minimushroom.src = "img/items/minimushroom.png";
	this.momsheels.src = "img/items/momsheels.png";
	this.momslipstick.src = "img/items/momslipstick.png";
	this.momsunderwear.src = "img/items/momsunderwear.png";
	this.numberone.src = "img/items/numberone.png";
	this.pyro.src = "img/items/pyro.png";
	this.rawliver.src = "img/items/rawliver.png";
	this.redheart.src = "img/items/redheart.png";
	this.roidrage.src = "img/items/roidrage.png";
	this.rottenmeat.src = "img/items/rottenmeat.png";
	this.skeletonkey.src = "img/items/skeletonkey.png";
	this.speedball.src = "img/items/speedball.png";
	this.thebelt.src = "img/items/thebelt.png";
	this.thehalo.src = "img/items/thehalo.png";
	this.thesadonion.src = "img/items/thesadonion.png";
	this.thesmallrock.src = "img/items/thesmallrock.png";
	this.toothpicks.src = "img/items/toothpicks.png";
	this.wirecoathanger.src = "img/items/wirecoathanger.png";
	this.woodenspoon.src = "img/items/woodenspoon.png";
	this.wiggleworm.src = "img/items/wiggleworm.png";
}
function Animation(maxframe,x,y,width,height,updatetime,spritesheet,offsetx,offsety,scale){
	this.frame= 0;
	this.maxFrame= maxframe;
	this.currentFrameTime=Date.now();
	this.lastFrameTime = Date.now();
	this.x= x;
	this.y= y;
	this.width=width;
	this.height=height;
	this.updateTime= updatetime;
	this.isOver = false;
	this.update= function(ux,uy){
		this.currentFrameTime= Date.now();
			if(this.currentFrameTime - this.lastFrameTime > this.updateTime){
				this.frame++;
				if (this.frame > this.maxFrame) this.frame = 0;
				this.lastFrameTime=Date.now();}
			this.x = ux;
			this.y = uy;
	}
	this.draw= function(context){
		
		context.drawImage(spritesheet,  this.frame*this.width, 0, this.width, this.height, this.x+offsetx, this.y+offsety, this.width/2, this.height/2);
		
	}
	this.playOnce = function(context){
		this.currentFrameTime= Date.now();
			if(this.currentFrameTime - this.lastFrameTime > this.updateTime){
				this.frame++;
				if (this.frame > this.maxFrame) this.isOver = true;
				this.lastFrameTime=Date.now();}
			this.x = x;
			this.y = y;
	}
	this.drawOnce = function(context){
		context.drawImage(spritesheet,  this.frame*this.width, 0, this.width, this.height, this.x+offsetx, this.y+offsety, this.width*scale, this.height*scale);
	}
}